name       : empathy
version    : 3.12.10
release    : 1
source     :
    - http://ftp.gnome.org/pub/gnome/sources/empathy/3.12/empathy-3.12.10.tar.xz : 794140c3743aa83739ef7efa9eff1950e2f718fde9dc29064fa9d616478e97cb
license    :
    - GPL-2.0
    - LGPL-2.1
    - CC-BY-NC-SA-3.0
    - GFDL-1.3
summary    : Empathy Instant Messing Client
description: |
    Gnome's Empathy Instant Messing Client
builddeps  :
    - pkgconfig(cheese-gtk)
    - pkgconfig(libsecret-1)
    - pkgconfig(telepathy-glib)
    - pkgconfig(folks)
    - pkgconfig(gnutls)
    - pkgconfig(telepathy-logger-0.2)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libnotify)
    - pkgconfig(gcr-3)
    - pkgconfig(libpulse)
    - pkgconfig(webkitgtk-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(gee-0.8)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
