name       : empathy
version    : 3.12.14
release    : 9
source     :
    - https://download.gnome.org/sources/empathy/3.12/empathy-3.12.14.tar.xz : 7d86942ce97edd10ade0e6ae6a210d35e4d627fe4d223377d71fd1840bc6e3a3
license    :
    - GPL-2.0
    - LGPL-2.1
    - CC-BY-NC-SA-3.0
    - GFDL-1.3
component  : network.im
summary    : Empathy Instant Messing Client
description: |
    Gnome's Empathy Instant Messing Client
builddeps  :
    - pkgconfig(accountsservice)
    - pkgconfig(champlain-0.12)
    - pkgconfig(cheese-gtk)
    - pkgconfig(clutter-gst-3.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(enchant)
    - pkgconfig(farstream-0.2)
    - pkgconfig(folks)
    - pkgconfig(goa-1.0)
    - pkgconfig(gcr-3)
    - pkgconfig(gee-0.8)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gsettings-desktop-schemas)
    - pkgconfig(ice)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(libgeoclue-2.0)
    - pkgconfig(libnotify)
    - pkgconfig(libpulse)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(telepathy-farstream)
    - pkgconfig(telepathy-glib)
    - pkgconfig(telepathy-logger-0.2)
    - pkgconfig(mission-control-plugins)
    - pkgconfig(webkit2gtk-4.0)
    - itstool
rundeps    :
    - telepathy-gabble
    - telepathy-haze
    - telepathy-idle
    - telepathy-rakia
    - telepathy-salut
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
